# Generated by Django 4.2 on 2024-03-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('doctor_name', models.CharField(max_length=255)),
                ('doctor_specialization', models.CharField(max_length=255)),
                ('patient_problem', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField()),
            ],
            options={
                'verbose_name': 'appointment',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_address', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('patient_dob', models.DateField()),
                ('patient_phone', models.CharField(max_length=255)),
                ('patient_gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=255)),
                ('patient_diagonisis', models.TextField()),
            ],
        ),
    ]
