# Generated by Django 4.2 on 2024-03-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_appointments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointments',
            name='is_checked_by_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
