# Generated by Django 4.2 on 2024-04-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_appointments_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
