# Generated by Django 4.2 on 2024-04-01 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_appointments_appointment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='notes',
            new_name='doctor_dignosis',
        ),
        migrations.AddField(
            model_name='appointments',
            name='doctor_pescription',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
