# Generated by Django 4.2 on 2024-04-01 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0007_rename_notes_appointments_doctor_dignosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='user',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_doctor': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
