# Generated by Django 4.2 on 2024-04-01 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_appointments_doctor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='doctor_specialization',
        ),
    ]
