# Generated by Django 4.2 on 2024-04-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_bills_bill_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billsitems',
            name='qty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
