# Generated by Django 4.2 on 2024-04-04 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_billsitems_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='doctor_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
