# Generated by Django 4.2 on 2024-04-04 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_report_doctor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='patient_address',
        ),
        migrations.RemoveField(
            model_name='report',
            name='patient_address',
        ),
        migrations.RemoveField(
            model_name='report',
            name='patient_dob',
        ),
        migrations.RemoveField(
            model_name='report',
            name='patient_gender',
        ),
        migrations.RemoveField(
            model_name='report',
            name='patient_phone',
        ),
    ]
