# Generated by Django 4.2 on 2024-04-04 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0017_remove_bills_patient_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(blank=True, max_length=255, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('illness', models.TextField(blank=True, null=True)),
                ('surgery', models.TextField(blank=True, null=True)),
                ('medicine_taken', models.TextField(blank=True, null=True)),
                ('immunization', models.TextField(blank=True, null=True)),
                ('vitals', models.TextField(blank=True, null=True)),
                ('weight', models.CharField(blank=True, max_length=255, null=True)),
                ('heart_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('blood_pressure', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(limit_choices_to={'is_patient': True}, on_delete=django.db.models.deletion.CASCADE, related_name='patienthistory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
