# Generated by Django 4.2 on 2024-04-04 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_bills_options_alter_billsitems_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='paid_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bills',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billspatient', to='dashboard.appointments'),
        ),
    ]
