# Generated by Django 4.2 on 2024-04-06 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0020_bills_paid_status_alter_bills_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='pin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='patient',
            field=models.OneToOneField(limit_choices_to={'is_patient': True}, on_delete=django.db.models.deletion.CASCADE, related_name='patienthistory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
