# Generated by Django 4.2 on 2024-04-24 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_appointments_appointment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='patient_name',
        ),
    ]
