# Generated by Django 4.2 on 2024-04-04 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
